cache:
  npm: false
language: node_js
node_js: node
addons:
  chrome: stable
script:
- npm run lint
- |
  if [ $TRAVIS_PULL_REQUEST != false ] && [ $TRAVIS_SECURE_ENV_VARS == true ]; then
    echo "Pull request with secure environment variables, running Sauce tests...";
    npm run test:polymer:sauce || travis_terminate 1;
  else
    echo "Not a pull request and/or no secure environment variables, running headless tests...";
    npm run test:polymer:local || travis_terminate 1;
  fi
after_success:
- frauci-update-version -d=skip && export TRAVIS_TAG=$(frauci-get-version)
deploy:
  provider: releases
  api_key: "$GITHUB_RELEASE_TOKEN"
  on:
    tags: true
env:
  global:
  - OWNER_NAME=BrightspaceUI
  - REPO_NAME=navigation
  - SAUCE_USERNAME: Desire2Learn
  - secure: j7N5Mth+AY+MObVwsysDBWs8musd84uAcynODmnm3MmDin0yrG0HY63FBh9vKSqyOeu/pR4r6hcvMiQfybE37NK0HeeENMvanEAIIdqCdGPNGLU3OTu1W/Tci9XEVV9NdFDeZuVTU8+d1IaHPAMOPeWDBka3mNe1un9KSaiPSTyktIjxboR1k3mQ2ESUAyu5qW0UGeUQzWywNYZ1a6KbrpjhdjcSJ/kxwg4EDgsLZeI7QTQtx+jKDZPiCYH5b237dp0+to7kMMHmw37AQRnxfOayT7AhRKcgJh6snX3FgqdaOpgk0iZ/xldIqWBSPc7HEm/ZvLqq51kxUSdE4PCAiunARxo7GBnOXlYd9pGYYnFsn9vQrnPvp3WK1dGdCIQmDOq09z2C9Jh0End/xjB2lky7+FYK8g5tqxoz6gsHI80FHtY2uWwLo6MNGk38//9c980Q+XpK8G+qEZ+gfx8QnGsMg5Yl7NoXwEiJ9FmaQ2vRsybnCA/9OTHnPXWG3o1d4yNhVRRGUSnzUtuBJXPxmHhUxrVrYkYE/7pMmZjtkQH9P11uYcLXZsKaXlDd+m7yfY7rQXXZFslVuKS7LWcLWrbW3BHg0NwxrVrqi5NsttdU8vDlWgS3j1q+2tH5AgfRHn6T6aymXz/Vhv4pN7AVslu6I1Pdf6souyb56RUg/8o=
  - secure: K7KV8E3R4KSguZlMbXDxFTtSYWJYv5enPutjbXQdPrJ1kbRRAI/xRnRomNRXHtFOp9+FwysXXdrCV5ELvgPX85TfyjW+UiKFycq12gun2gKi5CrH7V4guP0m3MT+Ebcl/qC6ppPU9ey+9po+cw9M27unfIGJgqcfid32cQ3CdPXbQmX0VIu41E2rkx+PAh4E/GDHCk/DB2T9pKJkKwZMgmkzGF+a2/2saRagGirbAzfpooc4+WL6E7/6WONvPl9yCmO6lDBpGYad98HqYUC8AAS0h57vKeUKew92RNpJgl0QYvC5kV5bUgK2g0bVABRL8JvT8Ooyn7TZE1LY7DBrNDTqlayD5B8y4Xo/JfhHSsIZTQ/WK8gxy/JOk0OaDBEVCz8DYw1OjWLL4RsWMm/yNuaDvNANNT90V2mcLmFYR6yEI+3RW1AIMDpqD/s2ceNfmdV95D9ZU86AUMTpOxzrN4DIHLM8GOwXEA/u0pKh0FtLREEW28HudlIOzVlxqAA8a94y+T6YciktfSCVTYqrqTt+WTT6gCUzgUAPxUqZYNalPvRimlcj1f4XmNZhHEtXtXGlbXv1oZPKQdF0l26Lwdf24Ei2M2NABHm0QUyEGHts8CARewSEtpWnZZJ4IMSzzeZN5BeOhVecCgSDZgFrnoA5zJnnavwH8E9JcCrH68U=
